name: Update standalone branch

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  standalone:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: sudo apt-get install -y tree
    - name: configure
      run: cmake -H. -Bbuild/ -DCMAKE_INSTALL_PREFIX=${PWD}/install/
    - name: deploy
      run: cmake --build build/ --target install && tree ${PWD}/install/
    - name: release
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: standalone
        FOLDER: install/include
